# docker stack deploy -c docker-compose.yml scb-postgresql
version: '3.1'

services:
  db:
    image: postgres
    deploy:
      replicas: 1
    restart: unless-stopped
    environment:
      TZ: Asia/Seoul
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    ports:
      - 5432:5432
    secrets:
      - db_password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
secrets:
  db_password:
    file: ./db/postgresql_password

volumes:
  db_data: